project: pi3
snaps:
  kernel: pi2-kernel
  os: ubuntu-core
  gadget: pi3
configs:
  arch: armhf
  baseimage: base.img
  recoverytype: recovery
  recoverysize: 768
  release: 16
  channel: edge
  size: 4
  partition-type: mbr
  bootloader: u-boot
udf:
  binary: /snap/bin/ubuntu-device-flash
  command: core
debug:
  devmode: on
  ssh: on
  xz: off
recovery:
  partition-type: mbr
  filesystem-label: ESP
  boot-partition:
  systemboot-partition:
  writable-partition:
  boot-image:
  systemboot-image:
  writable-image:
  sign-serial: off
  sign-api-key: U2VyaWFsIFZhdWx0Cg
